### ISSUE TITLE
snap: could not build the snap for ARM

### ISSUE THREAD

**Issue by devimc** [kata-containers/packaging#982]
failed to build qemu:  **ERROR: static and pie are mutually incompatible**

https://launchpad.net/~kata-containers-dev/+snap/master/+build/876078
https://launchpadlibrarian.net/469884066/buildlog_snap_ubuntu_bionic_arm64_master_BUILDING.txt.gz

```
Cloning into 'ui/keycodemapdb'...
Cloning into 'capstone'...
[20/Mar/2020:20:17:16 +0000] "CONNECT github.com:443 HTTP/1.1" 200 110607 "-" "git/2.17.1"
[20/Mar/2020:20:17:25 +0000] "CONNECT github.com:443 HTTP/1.1" 200 43567790 "-" "git/2.17.1"
Applying 0001-qemu-gather-and-modification-of-the-whole-Eric-Auger.patch ...
patching file accel/kvm/kvm-all.c
patching file default-configs/aarch64-softmmu.mak
patching file default-configs/arm-softmmu.mak
patching file hw/acpi/aml-build.c
patching file hw/acpi/nvdimm.c
patching file hw/arm/boot.c
patching file hw/arm/virt-acpi-build.c
patching file hw/arm/virt.c
patching file hw/i386/pc_piix.c
patching file hw/i386/pc_q35.c
patching file hw/ppc/mac_newworld.c
patching file hw/ppc/mac_oldworld.c
patching file hw/ppc/spapr.c
patching file include/hw/acpi/aml-build.h
patching file include/hw/arm/virt.h
patching file include/hw/boards.h
patching file include/hw/mem/nvdimm.h
patching file linux-headers/linux/kvm.h
patching file target/arm/kvm.c
patching file target/arm/kvm_arm.h
patching file vl.c

ERROR: static and pie are mutually incompatible

Failed to run 'override-build': Exit code was 123.
Build failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/lpbuildd/target/build_snap.py", line 266, in run
    self.build()
  File "/usr/lib/python2.7/dist-packages/lpbuildd/target/build_snap.py", line 255, in build
    env=env)
  File "/usr/lib/python2.7/dist-packages/lpbuildd/target/build_snap.py", line 102, in run_build_command
    return self.backend.run(args, env=full_env, **kwargs)
  File "/usr/lib/python2.7/dist-packages/lpbuildd/target/lxd.py", line 536, in run
    subprocess.check_call(cmd, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['lxc', 'exec', 'lp-bionic-arm64', '--env', 'LANG=C.UTF-8', '--env', 'SHELL=/bin/sh', '--env', 'SNAPCRAFT_BUILD_INFO=1', '--env', 'SNAPCRAFT_IMAGE_INFO={"build_url": "https://launchpad.net/~kata-containers-dev/+snap/master/+build/876078"}', '--env', 'SNAPCRAFT_BUILD_ENVIRONMENT=host', '--env', 'http_proxy=http://10.10.10.1:8222/', '--env', 'https_proxy=http://10.10.10.1:8222/', '--env', 'GIT_PROXY_COMMAND=/usr/local/bin/snap-git-proxy', '--', '/bin/sh', '-c', 'cd /build/kata-containers && linux64 snapcraft']' returned non-zero exit status 2
Revoking proxy token...
RUN: /usr/share/launchpad-buildd/bin/in-target scan-for-processes --backend=lxd --series=bionic --arch=arm64 SNAPBUILD-876078
Scanning for processes to kill in build SNAPBUILD-876078
```

cc @Pennyzct @jongwu

**Comment by stevecapperarm** [comment]
This looks like a case where `-fno-pie` should be added to the CFLAGS at the same point as static? (Debian based gcc's are built using `--enable-default-pie` IIUC).

**Comment by justin-he** [comment]
Hi, --enable-pie should be removed when statically build qemu.

**Comment by justin-he** [comment]
I tested viwth "../../kata-containers/packaging/scripts/configure-hypervisor.sh -s qemu | xargs ./configure ". After this patch, no such configure error
